# -*- coding: utf-8 -*-
"""Textes du site, par langue. Modifie ici puis lance : python3 tools/build.py"""

# ---------------------------------------------------------------------------
# Configuration générale
# ---------------------------------------------------------------------------
SITE = {
    # Quand le nouveau domaine sera branché sur Vercel, remplace cette ligne
    # (ex. "https://www.lamaisondupecheur.fr") puis relance le build.
    "url": "https://peche-passion-site.vercel.app",
    "name": "La Maison du Pêcheur",
    "alt_name": "Pêche Passion Confort",
    "phone": "+33662107833",
    "phone_display": "06 62 10 78 33",
    "email": "lefebvre.florian54230@gmail.com",
    "street": "1295 rue de Pierreville",
    "postal": "54160",
    "city": "Pulligny",
    "region": "Grand Est",
    "country": "FR",
    "maps_link": "https://www.google.com/maps/search/?api=1&query=1295+rue+de+Pierreville+54160+Pulligny",
    "maps_embed": "https://www.google.com/maps?q=1295+rue+de+Pierreville,+54160+Pulligny&output=embed",
    "google_reviews": "https://www.google.com/maps/search/?api=1&query=Pêche+Passion+Confort+Pulligny",
    "gsc_meta": "Ix8mgSbluDuezH_6e8l5GTUpWn2dFQr6lM5UmLuq1zI",
}

UNITS = {
    "tiny": {
        "slug": "tiny-house",
        "calendar": "https://pechepassioncalendrier.vercel.app/api/merged?which=tiny",
        "airbnb": "https://www.airbnb.fr/rooms/701051727494324918",
        "booking": "https://www.booking.com/hotel/fr/tiny-house-detente-nature-la-maison-du-pecheur.html",
        "guests": 2,
        "size": 15,
        "cover": "tiny-house-chalet-bois",
        "photos": ["tiny-house-chalet-bois", "tiny-house-lit-double", "tiny-house-cuisine",
                   "tiny-house-douche", "tiny-house-tv", "tiny-house-exterieur-jardin"],
    },
    "studio": {
        "slug": "studio-perche",
        "calendar": "https://pechepassioncalendrier.vercel.app/api/merged?which=studio",
        "airbnb": "https://www.airbnb.fr/rooms/1017199225456476736",
        "booking": "https://www.booking.com/hotel/fr/riviere-et-jardin-a-vos-pieds.html",
        "guests": 4,
        "size": None,
        "cover": "studio-perche-terrasse-vue-riviere",
        "photos": ["studio-perche-terrasse-vue-riviere", "studio-perche-maison-escalier", "studio-perche-sejour",
                   "studio-perche-chambre", "studio-perche-cuisine", "studio-perche-douche"],
    },
}

SETTING_PHOTOS = ["cygnes-riviere-madon", "jardin-terrasse-riviere", "poste-de-peche-riviere",
                  "coin-detente-jardin", "chardonneret-mangeoire", "jardin-sous-la-neige"]

LANGS = ["fr", "en", "de", "nl"]
LANG_NAMES = {"fr": "Français", "en": "English", "de": "Deutsch", "nl": "Nederlands"}
LOCALES = {"fr": "fr_FR", "en": "en_GB", "de": "de_DE", "nl": "nl_NL"}

# ---------------------------------------------------------------------------
# Textes
# ---------------------------------------------------------------------------
T = {}

T["fr"] = {
    "tagline": "Tiny House & Studio au bord de la rivière à Pulligny",
    "nav_tiny": "Tiny House", "nav_studio": "Studio Perché", "nav_setting": "Le cadre",
    "nav_access": "Accès", "nav_contact": "Contact", "book": "Réserver",
    "skip": "Aller au contenu",
    "home_title": "Gîte au bord de l'eau près de Nancy — Tiny House & Studio",
    "home_desc": "Deux hébergements au calme au bord du Madon à Pulligny, à 20 min de Nancy : une Tiny House pour 2 et un Studio Perché pour 4. Pêche, nature, parking privé, Wi-Fi rapide.",
    "hero_kicker": "Pulligny · Meurthe-et-Moselle · 20 min de Nancy",
    "hero_h1": "Dormir au bord de la rivière, au calme, près de Nancy",
    "hero_p": "Deux logements dans un grand jardin qui descend jusqu'au Madon : une Tiny House en bois pour deux et un Studio Perché avec terrasse pour quatre. Idéal pour une pause nature, une partie de pêche, un déplacement pro ou une étape sur la route du Sud.",
    "hero_cta1": "Voir les logements", "hero_cta2": "Disponibilités",
    "badge": "Superhôte Airbnb · plus de 280 avis",
    "units_h2": "Nos deux hébergements",
    "guests": "{n} voyageurs", "m2": "{n} m²",
    "see_unit": "Découvrir",
    "setting_h2": "Le cadre : jardin, rivière et pêche",
    "setting_p": "Le jardin borde directement le Madon. On y croise des cygnes et une foule d'oiseaux ; on y pêche depuis la berge, on lit sous le grand chêne, on écoute les vrais bruits de la nature. Ici, pas de vis-à-vis ni de bruit de ville.",
    "setting_list": ["Accès direct à la rivière depuis le jardin", "Pêche au bord de l'eau (carte de pêche requise)", "Coins détente et salon de jardin", "Parking privé sur place, voitures et motos"],
    "road_h2": "Une étape idéale sur la route du Sud",
    "road_p": "Vous venez d'Allemagne, des Pays-Bas, de Belgique ou du Luxembourg et descendez vers la Méditerranée ? Pulligny est à quelques minutes de l'axe Metz–Nancy–Dijon. Garez-vous au calme, dormez au bord de l'eau, et repartez reposé le lendemain.",
    "road_list": ["Parking privé et sécurisé", "Arrivée tardive possible", "Wi-Fi rapide"],
    "pro_h2": "Pour les déplacements professionnels",
    "pro_p": "À 20 minutes de Nancy et proche de Neuves-Maisons, Toul et Lunéville. Le Studio Perché dispose d'un bureau ; les deux logements ont le Wi-Fi rapide et une cuisine équipée pour les séjours de plusieurs nuits.",
    "reviews_h2": "Ce qu'en disent nos voyageurs",
    "reviews_p": "Florian est Superhôte sur Airbnb, avec plus de 280 avis. Les voyageurs citent surtout la propreté, l'accueil, le calme et l'emplacement au bord de l'eau. Lisez les avis directement sur les plateformes :",
    "rv_airbnb_tiny": "Avis Airbnb — Tiny House", "rv_airbnb_studio": "Avis Airbnb — Studio",
    "rv_booking_tiny": "Avis Booking — Tiny House", "rv_booking_studio": "Avis Booking — Studio",
    "rv_google": "Avis Google",
    "access_h2": "Accès",
    "access_list": ["Nancy : environ 20 min", "Neuves-Maisons : 10 min", "Toul et Lunéville : environ 30 min", "Massif des Vosges : environ 1 h"],
    "open_maps": "Ouvrir dans Google Maps",
    "faq_h2": "Questions fréquentes",
    "faq": [
        ("Peut-on pêcher sur place ?", "Oui, le jardin donne directement sur le Madon. Une carte de pêche valable en Meurthe-et-Moselle est nécessaire ; elle s'achète en ligne sur cartedepeche.fr."),
        ("Y a-t-il un parking ?", "Oui, un parking privé est disponible sur place, pour les voitures comme pour les motos."),
        ("Peut-on arriver tard le soir ?", "Oui, une arrivée tardive est possible. Prévenez-nous simplement de votre heure d'arrivée."),
        ("Comment réserver ?", "Réservez sur Airbnb ou Booking via les boutons de chaque logement, ou contactez-nous directement par téléphone ou e-mail."),
    ],
    "contact_h2": "Contact",
    "contact_p": "Une question, une demande pour un séjour long ou professionnel ? Appelez ou écrivez-nous.",
    "footer_rights": "Tous droits réservés.",
    "lang_label": "Langue",
    # Pages logement
    "avail_h2": "Disponibilités",
    "avail_note": "Calendrier mis à jour automatiquement depuis Airbnb et Booking. Les dates grisées sont déjà réservées.",
    "avail_err": "Le calendrier n'a pas pu être chargé. Consultez les disponibilités sur Airbnb ou Booking.",
    "book_airbnb": "Réserver sur Airbnb", "book_booking": "Réserver sur Booking",
    "features_h2": "Équipements",
    "other_unit": "Voir aussi",
    "back_home": "Accueil",
    "gallery_label": "Photos",
    "close": "Fermer", "prev": "Précédente", "next": "Suivante",
    "tiny": {
        "name": "Tiny House",
        "title": "Tiny House au bord de la rivière à Pulligny (2 pers.) — près de Nancy",
        "desc": "Chalet en bois de 15 m² pour 2 au bord du Madon à Pulligny : lit double, cuisine équipée, douche, Wi-Fi rapide, parking privé. Pêche et nature à 20 min de Nancy.",
        "h1": "Tiny House : un chalet en bois pour deux, au bord de l'eau",
        "short": "Chalet en bois de 15 m² pour deux, bien isolé, dans le jardin au bord du Madon.",
        "intro": "Notre Tiny House est un petit chalet en bois de 15 m², bien isolé, posé dans le jardin face à la rivière. Tout y est pensé pour le confort d'un couple ou d'un voyageur seul : un vrai lit double, une cuisine complète et une salle d'eau moderne. Laissez-vous bercer par les vrais sons de la nature.",
        "features": ["1 lit double", "Cuisine équipée : plaques, four, hotte, micro-ondes, réfrigérateur", "Salle d'eau avec douche et WC", "Télévision", "Wi-Fi rapide", "Vue sur le jardin et la rivière", "Parking privé (voitures et motos)", "Accès à la rivière pour la pêche"],
        "alts": ["Tiny House en bois dans le jardin à Pulligny", "Lit double de la Tiny House", "Cuisine équipée de la Tiny House", "Douche de la Tiny House", "Coin télévision de la Tiny House", "Extérieur de la Tiny House et réserve de bois"],
    },
    "studio": {
        "name": "Studio Perché",
        "title": "Studio Perché avec terrasse vue rivière à Pulligny (4 pers.) — près de Nancy",
        "desc": "Studio à l'étage pour 4 avec terrasse sur le Madon à Pulligny : lit king size, canapé-lit, lit bébé, cuisine, bureau, Wi-Fi rapide. À 20 min de Nancy.",
        "h1": "Studio Perché : terrasse sur la rivière, jusqu'à quatre personnes",
        "short": "Studio à l'étage avec terrasse et vue sur la rivière, jusqu'à 4 voyageurs.",
        "intro": "Le Studio Perché occupe l'étage de la maison, avec son entrée indépendante par un escalier en colimaçon. Depuis la terrasse, la vue plonge sur le jardin et la rivière. Le séjour ouvert avec cuisine et bureau convient aussi bien aux familles qu'aux voyageurs en télétravail.",
        "features": ["Chambre avec lit king size", "Canapé-lit dans le séjour", "Lit bébé disponible", "Cuisine équipée : plaques, four, micro-ondes, réfrigérateur", "Salle d'eau avec cabine de douche hydromassante", "Bureau pour le télétravail", "Wi-Fi rapide", "Terrasse avec vue sur la rivière", "Entrée indépendante", "Parking privé"],
        "alts": ["Terrasse du Studio Perché avec vue sur la rivière", "Maison et escalier extérieur menant au Studio Perché", "Séjour du Studio Perché avec canapé-lit et bureau", "Chambre du Studio Perché avec grand lit", "Cuisine du Studio Perché", "Cabine de douche du Studio Perché"],
    },
    "setting_alts": ["Cygnes sur le Madon au fond du jardin", "Jardin et terrasse au bord de la rivière", "Poste de pêche sur la berge", "Coin détente sous les arbres", "Chardonneret sur la mangeoire", "Le jardin sous la neige en hiver"],
    "hero_alt": "Vue aérienne de la propriété au bord de la rivière à Pulligny",
}

T["en"] = {
    "tagline": "Tiny House & Studio by the river in Pulligny",
    "nav_tiny": "Tiny House", "nav_studio": "Studio Perché", "nav_setting": "Surroundings",
    "nav_access": "Getting here", "nav_contact": "Contact", "book": "Book",
    "skip": "Skip to content",
    "home_title": "Riverside holiday rental near Nancy, France — Tiny House & Studio",
    "home_desc": "Tiny House for 2 and Studio for 4 by the river in Pulligny, 20 min from Nancy. Fishing, nature, private parking, fast Wi-Fi. Ideal stopover on the way to southern France.",
    "hero_kicker": "Pulligny · Lorraine · 20 min from Nancy",
    "hero_h1": "Sleep by the river, in peace, near Nancy",
    "hero_p": "Two places to stay in a large garden that runs down to the Madon river: a wooden Tiny House for two and a Studio with a terrace for four. Ideal for a nature break, a spot of fishing, a business trip or an overnight stop on the way south.",
    "hero_cta1": "See the rentals", "hero_cta2": "Availability",
    "badge": "Airbnb Superhost · 280+ reviews",
    "units_h2": "Our two rentals",
    "guests": "{n} guests", "m2": "{n} m²",
    "see_unit": "Discover",
    "setting_h2": "The setting: garden, river and fishing",
    "setting_p": "The garden runs straight down to the Madon river. Swans and plenty of birds are regular visitors; you can fish from the bank, read under the big oak tree and listen to nothing but nature. No neighbours overlooking you, no city noise.",
    "setting_list": ["Direct river access from the garden", "Bank fishing (fishing licence required)", "Garden furniture and quiet corners", "Private on-site parking for cars and motorbikes"],
    "road_h2": "The ideal stopover on the way south",
    "road_p": "Driving from the Netherlands, Germany, Belgium or Luxembourg towards the Mediterranean? Pulligny is just minutes from the Metz–Nancy–Dijon route. Park in peace, sleep by the water and set off rested the next morning.",
    "road_list": ["Private, secure parking", "Late arrivals welcome", "Fast Wi-Fi"],
    "pro_h2": "For business travellers",
    "pro_p": "20 minutes from Nancy and close to Neuves-Maisons, Toul and Lunéville. The Studio has a desk; both rentals have fast Wi-Fi and a fully equipped kitchen for longer stays.",
    "reviews_h2": "What our guests say",
    "reviews_p": "Florian is an Airbnb Superhost with more than 280 reviews. Guests mostly mention cleanliness, hospitality, the peace and quiet and the riverside location. Read the reviews on the platforms:",
    "rv_airbnb_tiny": "Airbnb reviews — Tiny House", "rv_airbnb_studio": "Airbnb reviews — Studio",
    "rv_booking_tiny": "Booking reviews — Tiny House", "rv_booking_studio": "Booking reviews — Studio",
    "rv_google": "Google reviews",
    "access_h2": "Getting here",
    "access_list": ["Nancy: about 20 min", "Neuves-Maisons: 10 min", "Toul and Lunéville: about 30 min", "Vosges mountains: about 1 hour"],
    "open_maps": "Open in Google Maps",
    "faq_h2": "Frequently asked questions",
    "faq": [
        ("Can I fish on site?", "Yes, the garden opens directly onto the Madon river. You need a fishing licence valid in Meurthe-et-Moselle, available online at cartedepeche.fr."),
        ("Is there parking?", "Yes, there is private parking on site for cars and motorbikes."),
        ("Can I arrive late in the evening?", "Yes, late arrivals are possible. Just let us know your arrival time."),
        ("How do I book?", "Book on Airbnb or Booking.com using the buttons on each rental page, or contact us directly by phone or e-mail."),
    ],
    "contact_h2": "Contact",
    "contact_p": "Any questions, or a request for a long or business stay? Call or write to us.",
    "footer_rights": "All rights reserved.",
    "lang_label": "Language",
    "avail_h2": "Availability",
    "avail_note": "Calendar synced automatically from Airbnb and Booking.com. Greyed-out dates are already booked.",
    "avail_err": "The calendar could not be loaded. Please check availability on Airbnb or Booking.com.",
    "book_airbnb": "Book on Airbnb", "book_booking": "Book on Booking.com",
    "features_h2": "Amenities",
    "other_unit": "See also",
    "back_home": "Home",
    "gallery_label": "Photos",
    "close": "Close", "prev": "Previous", "next": "Next",
    "tiny": {
        "name": "Tiny House",
        "title": "Riverside Tiny House for 2 in Pulligny, near Nancy (France)",
        "desc": "15 m² wooden cabin for 2 by the Madon river in Pulligny: double bed, equipped kitchen, shower, fast Wi-Fi, private parking. Fishing and nature, 20 min from Nancy.",
        "h1": "Tiny House: a wooden cabin for two by the water",
        "short": "A well-insulated 15 m² wooden cabin for two, in the garden by the river.",
        "intro": "Our Tiny House is a small, well-insulated 15 m² wooden cabin set in the garden facing the river. Everything is designed for a couple or a solo traveller: a proper double bed, a full kitchen and a modern shower room. Let the real sounds of nature lull you to sleep.",
        "features": ["1 double bed", "Equipped kitchen: hob, oven, hood, microwave, fridge", "Shower room with toilet", "TV", "Fast Wi-Fi", "Garden and river view", "Private parking (cars and motorbikes)", "River access for fishing"],
        "alts": ["Wooden Tiny House in the garden in Pulligny", "Double bed in the Tiny House", "Equipped kitchen in the Tiny House", "Shower in the Tiny House", "TV corner in the Tiny House", "Outside of the Tiny House with log store"],
    },
    "studio": {
        "name": "Studio Perché",
        "title": "Studio with river-view terrace in Pulligny (4 guests), near Nancy",
        "desc": "Upstairs studio for 4 with a terrace over the Madon river in Pulligny: king-size bed, sofa bed, baby cot, kitchen, desk, fast Wi-Fi. 20 min from Nancy.",
        "h1": "Studio Perché: a terrace above the river, for up to four",
        "short": "Upstairs studio with a terrace and river view, for up to 4 guests.",
        "intro": "The Studio Perché (\"perched studio\") takes up the upper floor of the house, with its own entrance via a spiral staircase. From the terrace you look out over the garden and the river. The open-plan living area with kitchen and desk suits families and remote workers alike.",
        "features": ["Bedroom with king-size bed", "Sofa bed in the living area", "Baby cot available", "Equipped kitchen: hob, oven, microwave, fridge", "Shower room with hydromassage shower", "Desk for remote work", "Fast Wi-Fi", "Terrace with river view", "Private entrance", "Private parking"],
        "alts": ["Studio Perché terrace overlooking the river", "House and outdoor staircase leading to the Studio", "Studio living area with sofa bed and desk", "Studio bedroom with large bed", "Studio kitchen", "Studio shower"],
    },
    "setting_alts": ["Swans on the Madon river at the bottom of the garden", "Garden and terrace by the river", "Fishing spot on the river bank", "Quiet corner under the trees", "Goldfinch on the bird feeder", "The garden under snow in winter"],
    "hero_alt": "Aerial view of the riverside property in Pulligny",
}

T["de"] = {
    "tagline": "Tiny House & Studio am Fluss in Pulligny",
    "nav_tiny": "Tiny House", "nav_studio": "Studio Perché", "nav_setting": "Umgebung",
    "nav_access": "Anfahrt", "nav_contact": "Kontakt", "book": "Buchen",
    "skip": "Zum Inhalt springen",
    "home_title": "Ferienunterkunft am Fluss bei Nancy — Tiny House & Studio",
    "home_desc": "Tiny House für 2 und Studio für 4 am Fluss in Pulligny, 20 Min. von Nancy. Angeln, Natur, Privatparkplatz, WLAN. Idealer Zwischenstopp nach Südfrankreich.",
    "hero_kicker": "Pulligny · Lothringen · 20 Min. von Nancy",
    "hero_h1": "Ruhig übernachten am Fluss, nahe Nancy",
    "hero_p": "Zwei Unterkünfte in einem großen Garten, der bis an den Fluss Madon reicht: ein Tiny House aus Holz für zwei und ein Studio mit Terrasse für vier. Ideal für eine Auszeit in der Natur, zum Angeln, für Geschäftsreisen oder als Zwischenstopp auf dem Weg in den Süden.",
    "hero_cta1": "Unterkünfte ansehen", "hero_cta2": "Verfügbarkeit",
    "badge": "Airbnb Superhost · über 280 Bewertungen",
    "units_h2": "Unsere zwei Unterkünfte",
    "guests": "{n} Gäste", "m2": "{n} m²",
    "see_unit": "Entdecken",
    "setting_h2": "Die Umgebung: Garten, Fluss und Angeln",
    "setting_p": "Der Garten grenzt direkt an den Fluss Madon. Schwäne und viele Vögel sind hier zu Hause; man angelt vom Ufer aus, liest unter der großen Eiche und hört nur die Geräusche der Natur. Keine Nachbarn, kein Stadtlärm.",
    "setting_list": ["Direkter Flusszugang vom Garten", "Angeln am Ufer (Angelschein erforderlich)", "Gartenmöbel und ruhige Ecken", "Privatparkplatz für Autos und Motorräder"],
    "road_h2": "Der ideale Zwischenstopp nach Südfrankreich",
    "road_p": "Sie fahren aus Deutschland, den Niederlanden, Belgien oder Luxemburg ans Mittelmeer? Pulligny liegt nur wenige Minuten von der Achse Metz–Nancy–Dijon entfernt. Ruhig parken, am Wasser schlafen und am nächsten Morgen erholt weiterfahren.",
    "road_list": ["Privater, sicherer Parkplatz", "Späte Ankunft möglich", "Schnelles WLAN"],
    "pro_h2": "Für Geschäftsreisende",
    "pro_p": "20 Minuten von Nancy, nahe Neuves-Maisons, Toul und Lunéville. Das Studio hat einen Schreibtisch; beide Unterkünfte bieten schnelles WLAN und eine voll ausgestattete Küche für längere Aufenthalte.",
    "reviews_h2": "Das sagen unsere Gäste",
    "reviews_p": "Florian ist Airbnb-Superhost mit über 280 Bewertungen. Gäste loben vor allem Sauberkeit, Gastfreundschaft, Ruhe und die Lage am Wasser. Lesen Sie die Bewertungen direkt auf den Plattformen:",
    "rv_airbnb_tiny": "Airbnb-Bewertungen — Tiny House", "rv_airbnb_studio": "Airbnb-Bewertungen — Studio",
    "rv_booking_tiny": "Booking-Bewertungen — Tiny House", "rv_booking_studio": "Booking-Bewertungen — Studio",
    "rv_google": "Google-Bewertungen",
    "access_h2": "Anfahrt",
    "access_list": ["Nancy: ca. 20 Min.", "Neuves-Maisons: 10 Min.", "Toul und Lunéville: ca. 30 Min.", "Vogesen: ca. 1 Std."],
    "open_maps": "In Google Maps öffnen",
    "faq_h2": "Häufige Fragen",
    "faq": [
        ("Kann man vor Ort angeln?", "Ja, der Garten liegt direkt am Fluss Madon. Sie benötigen einen für das Département Meurthe-et-Moselle gültigen Angelschein, erhältlich online auf cartedepeche.fr."),
        ("Gibt es einen Parkplatz?", "Ja, es gibt einen Privatparkplatz vor Ort für Autos und Motorräder."),
        ("Kann ich spät abends ankommen?", "Ja, eine späte Ankunft ist möglich. Teilen Sie uns einfach Ihre Ankunftszeit mit."),
        ("Wie kann ich buchen?", "Buchen Sie über Airbnb oder Booking.com mit den Schaltflächen auf jeder Unterkunftsseite oder kontaktieren Sie uns direkt per Telefon oder E-Mail."),
    ],
    "contact_h2": "Kontakt",
    "contact_p": "Fragen oder Anfragen für längere Aufenthalte oder Geschäftsreisen? Rufen Sie an oder schreiben Sie uns.",
    "footer_rights": "Alle Rechte vorbehalten.",
    "lang_label": "Sprache",
    "avail_h2": "Verfügbarkeit",
    "avail_note": "Kalender automatisch mit Airbnb und Booking.com synchronisiert. Ausgegraute Daten sind bereits belegt.",
    "avail_err": "Der Kalender konnte nicht geladen werden. Bitte prüfen Sie die Verfügbarkeit auf Airbnb oder Booking.com.",
    "book_airbnb": "Auf Airbnb buchen", "book_booking": "Auf Booking.com buchen",
    "features_h2": "Ausstattung",
    "other_unit": "Siehe auch",
    "back_home": "Startseite",
    "gallery_label": "Fotos",
    "close": "Schließen", "prev": "Zurück", "next": "Weiter",
    "tiny": {
        "name": "Tiny House",
        "title": "Tiny House am Fluss in Pulligny für 2 Personen — nahe Nancy",
        "desc": "15 m² Holzhaus für 2 am Fluss Madon in Pulligny: Doppelbett, ausgestattete Küche, Dusche, schnelles WLAN, Privatparkplatz. Angeln und Natur, 20 Min. von Nancy.",
        "h1": "Tiny House: ein Holzhäuschen für zwei am Wasser",
        "short": "Gut isoliertes 15 m² Holzhaus für zwei, im Garten am Fluss.",
        "intro": "Unser Tiny House ist ein kleines, gut isoliertes Holzhaus mit 15 m², mitten im Garten mit Blick auf den Fluss. Alles ist auf ein Paar oder Alleinreisende ausgelegt: ein richtiges Doppelbett, eine komplette Küche und ein modernes Duschbad. Lassen Sie sich von den echten Geräuschen der Natur in den Schlaf wiegen.",
        "features": ["1 Doppelbett", "Ausgestattete Küche: Kochfeld, Backofen, Dunstabzug, Mikrowelle, Kühlschrank", "Duschbad mit WC", "Fernseher", "Schnelles WLAN", "Blick auf Garten und Fluss", "Privatparkplatz (Autos und Motorräder)", "Flusszugang zum Angeln"],
        "alts": ["Tiny House aus Holz im Garten in Pulligny", "Doppelbett im Tiny House", "Ausgestattete Küche im Tiny House", "Dusche im Tiny House", "Fernsehecke im Tiny House", "Außenansicht des Tiny House mit Holzlager"],
    },
    "studio": {
        "name": "Studio Perché",
        "title": "Studio mit Terrasse und Flussblick in Pulligny für 4 Personen — nahe Nancy",
        "desc": "Studio im Obergeschoss für 4 mit Terrasse über dem Fluss Madon in Pulligny: Kingsize-Bett, Schlafsofa, Babybett, Küche, Schreibtisch, schnelles WLAN. 20 Min. von Nancy.",
        "h1": "Studio Perché: Terrasse über dem Fluss, für bis zu vier Personen",
        "short": "Studio im Obergeschoss mit Terrasse und Flussblick, für bis zu 4 Gäste.",
        "intro": "Das Studio Perché liegt im Obergeschoss des Hauses und hat einen eigenen Eingang über eine Wendeltreppe. Von der Terrasse blicken Sie über den Garten und den Fluss. Der offene Wohnbereich mit Küche und Schreibtisch eignet sich für Familien ebenso wie für Gäste im Homeoffice.",
        "features": ["Schlafzimmer mit Kingsize-Bett", "Schlafsofa im Wohnbereich", "Babybett vorhanden", "Ausgestattete Küche: Kochfeld, Backofen, Mikrowelle, Kühlschrank", "Duschbad mit Hydromassage-Dusche", "Schreibtisch fürs Homeoffice", "Schnelles WLAN", "Terrasse mit Flussblick", "Eigener Eingang", "Privatparkplatz"],
        "alts": ["Terrasse des Studio Perché mit Blick auf den Fluss", "Haus mit Außentreppe zum Studio", "Wohnbereich des Studios mit Schlafsofa und Schreibtisch", "Schlafzimmer des Studios mit großem Bett", "Küche des Studios", "Dusche des Studios"],
    },
    "setting_alts": ["Schwäne auf dem Fluss Madon am Ende des Gartens", "Garten und Terrasse am Fluss", "Angelplatz am Ufer", "Ruhige Ecke unter den Bäumen", "Stieglitz am Futterhaus", "Der Garten im Winter unter Schnee"],
    "hero_alt": "Luftaufnahme des Anwesens am Fluss in Pulligny",
}

T["nl"] = {
    "tagline": "Tiny House & Studio aan de rivier in Pulligny",
    "nav_tiny": "Tiny House", "nav_studio": "Studio Perché", "nav_setting": "Omgeving",
    "nav_access": "Route", "nav_contact": "Contact", "book": "Boeken",
    "skip": "Naar de inhoud",
    "home_title": "Vakantieverblijf aan de rivier bij Nancy — Tiny House & Studio",
    "home_desc": "Tiny House voor 2 en Studio voor 4 aan de rivier in Pulligny, 20 min van Nancy. Vissen, natuur, eigen parkeerplaats, wifi. Ideale tussenstop naar Zuid-Frankrijk.",
    "hero_kicker": "Pulligny · Lotharingen · 20 min van Nancy",
    "hero_h1": "Rustig overnachten aan de rivier, vlak bij Nancy",
    "hero_p": "Twee verblijven in een grote tuin die doorloopt tot aan de rivier de Madon: een houten Tiny House voor twee en een Studio met terras voor vier. Ideaal voor een natuuruitje, om te vissen, voor een zakenreis of als tussenstop op weg naar het zuiden.",
    "hero_cta1": "Bekijk de verblijven", "hero_cta2": "Beschikbaarheid",
    "badge": "Airbnb Superhost · meer dan 280 beoordelingen",
    "units_h2": "Onze twee verblijven",
    "guests": "{n} gasten", "m2": "{n} m²",
    "see_unit": "Ontdekken",
    "setting_h2": "De omgeving: tuin, rivier en vissen",
    "setting_p": "De tuin grenst direct aan de rivier de Madon. Zwanen en veel vogels komen hier langs; u vist vanaf de oever, leest onder de grote eik en hoort alleen de geluiden van de natuur. Geen inkijk, geen stadslawaai.",
    "setting_list": ["Directe toegang tot de rivier vanuit de tuin", "Vissen vanaf de oever (visvergunning vereist)", "Tuinmeubels en rustige plekjes", "Eigen parkeerplaats voor auto's en motoren"],
    "road_h2": "De ideale tussenstop op weg naar het zuiden",
    "road_p": "Rijdt u vanuit Nederland, België, Duitsland of Luxemburg naar de Middellandse Zee? Pulligny ligt op een paar minuten van de route Metz–Nancy–Dijon. Parkeer rustig, slaap aan het water en vertrek de volgende ochtend uitgerust.",
    "road_list": ["Eigen, veilige parkeerplaats", "Laat aankomen mogelijk", "Snelle wifi"],
    "pro_h2": "Voor zakenreizigers",
    "pro_p": "20 minuten van Nancy, dicht bij Neuves-Maisons, Toul en Lunéville. De Studio heeft een bureau; beide verblijven hebben snelle wifi en een volledig uitgeruste keuken voor langere verblijven.",
    "reviews_h2": "Wat onze gasten zeggen",
    "reviews_p": "Florian is Superhost op Airbnb met meer dan 280 beoordelingen. Gasten noemen vooral de netheid, de gastvrijheid, de rust en de ligging aan het water. Lees de beoordelingen op de platforms:",
    "rv_airbnb_tiny": "Airbnb-beoordelingen — Tiny House", "rv_airbnb_studio": "Airbnb-beoordelingen — Studio",
    "rv_booking_tiny": "Booking-beoordelingen — Tiny House", "rv_booking_studio": "Booking-beoordelingen — Studio",
    "rv_google": "Google-beoordelingen",
    "access_h2": "Route",
    "access_list": ["Nancy: ongeveer 20 min", "Neuves-Maisons: 10 min", "Toul en Lunéville: ongeveer 30 min", "Vogezen: ongeveer 1 uur"],
    "open_maps": "Openen in Google Maps",
    "faq_h2": "Veelgestelde vragen",
    "faq": [
        ("Kan ik ter plaatse vissen?", "Ja, de tuin ligt direct aan de rivier de Madon. U heeft een visvergunning nodig die geldig is in Meurthe-et-Moselle, online te koop op cartedepeche.fr."),
        ("Is er een parkeerplaats?", "Ja, er is een eigen parkeerplaats ter plaatse voor auto's en motoren."),
        ("Kan ik laat op de avond aankomen?", "Ja, laat aankomen is mogelijk. Laat ons gewoon uw aankomsttijd weten."),
        ("Hoe kan ik boeken?", "Boek via Airbnb of Booking.com met de knoppen op elke verblijfspagina, of neem rechtstreeks contact met ons op per telefoon of e-mail."),
    ],
    "contact_h2": "Contact",
    "contact_p": "Vragen, of een aanvraag voor een lang verblijf of zakenreis? Bel of schrijf ons.",
    "footer_rights": "Alle rechten voorbehouden.",
    "lang_label": "Taal",
    "avail_h2": "Beschikbaarheid",
    "avail_note": "Kalender automatisch gesynchroniseerd met Airbnb en Booking.com. Grijze data zijn al geboekt.",
    "avail_err": "De kalender kon niet worden geladen. Bekijk de beschikbaarheid op Airbnb of Booking.com.",
    "book_airbnb": "Boeken op Airbnb", "book_booking": "Boeken op Booking.com",
    "features_h2": "Voorzieningen",
    "other_unit": "Zie ook",
    "back_home": "Home",
    "gallery_label": "Foto's",
    "close": "Sluiten", "prev": "Vorige", "next": "Volgende",
    "tiny": {
        "name": "Tiny House",
        "title": "Tiny House aan de rivier in Pulligny voor 2 personen — bij Nancy",
        "desc": "Houten huisje van 15 m² voor 2 aan de rivier de Madon in Pulligny: tweepersoonsbed, uitgeruste keuken, douche, snelle wifi, eigen parkeerplaats. Vissen en natuur, 20 min van Nancy.",
        "h1": "Tiny House: een houten huisje voor twee aan het water",
        "short": "Goed geïsoleerd houten huisje van 15 m² voor twee, in de tuin aan de rivier.",
        "intro": "Onze Tiny House is een klein, goed geïsoleerd houten huisje van 15 m², in de tuin met uitzicht op de rivier. Alles is ingericht voor een stel of een solo-reiziger: een echt tweepersoonsbed, een complete keuken en een moderne badkamer. Laat u in slaap wiegen door de echte geluiden van de natuur.",
        "features": ["1 tweepersoonsbed", "Uitgeruste keuken: kookplaat, oven, afzuigkap, magnetron, koelkast", "Badkamer met douche en toilet", "Televisie", "Snelle wifi", "Uitzicht op tuin en rivier", "Eigen parkeerplaats (auto's en motoren)", "Toegang tot de rivier om te vissen"],
        "alts": ["Houten Tiny House in de tuin in Pulligny", "Tweepersoonsbed in de Tiny House", "Uitgeruste keuken in de Tiny House", "Douche in de Tiny House", "Tv-hoek in de Tiny House", "Buitenkant van de Tiny House met houtopslag"],
    },
    "studio": {
        "name": "Studio Perché",
        "title": "Studio met terras en rivierzicht in Pulligny voor 4 personen — bij Nancy",
        "desc": "Studio op de verdieping voor 4 met terras boven de rivier de Madon in Pulligny: kingsize bed, slaapbank, babybedje, keuken, bureau, snelle wifi. 20 min van Nancy.",
        "h1": "Studio Perché: een terras boven de rivier, voor maximaal vier personen",
        "short": "Studio op de verdieping met terras en rivierzicht, voor maximaal 4 gasten.",
        "intro": "De Studio Perché beslaat de bovenverdieping van het huis, met een eigen ingang via een wenteltrap. Vanaf het terras kijkt u uit over de tuin en de rivier. De open woonruimte met keuken en bureau is geschikt voor gezinnen én voor wie op afstand werkt.",
        "features": ["Slaapkamer met kingsize bed", "Slaapbank in de woonruimte", "Babybedje aanwezig", "Uitgeruste keuken: kookplaat, oven, magnetron, koelkast", "Badkamer met hydromassagedouche", "Bureau om op afstand te werken", "Snelle wifi", "Terras met uitzicht op de rivier", "Eigen ingang", "Eigen parkeerplaats"],
        "alts": ["Terras van de Studio Perché met uitzicht op de rivier", "Huis met buitentrap naar de Studio", "Woonruimte van de Studio met slaapbank en bureau", "Slaapkamer van de Studio met groot bed", "Keuken van de Studio", "Douche van de Studio"],
    },
    "setting_alts": ["Zwanen op de Madon onderaan de tuin", "Tuin en terras aan de rivier", "Visplek op de oever", "Rustig plekje onder de bomen", "Putter op de voederplank", "De tuin onder de sneeuw in de winter"],
    "hero_alt": "Luchtfoto van het terrein aan de rivier in Pulligny",
}
